[package]
id = "org.mochios.coreutils"
name = "coreutils"
version = "0.1.0"
vendor = "mochiOS Project"

[[binary]]
path = "/bin/echo"
capability_profile = "coreutils.echo"
kind = "application"

[[binary]]
path = "/bin/ls"
capability_profile = "coreutils.ls"
kind = "application"

[[binary]]
path = "/bin/pwd"
capability_profile = "coreutils.pwd"
kind = "application"

[[binary]]
path = "/bin/true"
capability_profile = "coreutils.true"
kind = "application"

[[binary]]
path = "/bin/false"
capability_profile = "coreutils.false"
kind = "application"

[[binary]]
path = "/bin/cat"
capability_profile = "coreutils.cat"
kind = "application"

[[binary]]
path = "/bin/touch"
capability_profile = "coreutils.touch"
kind = "application"

[[binary]]
path = "/bin/rm"
capability_profile = "coreutils.rm"
kind = "application"

[[binary]]
path = "/bin/id"
capability_profile = "coreutils.id"
kind = "application"

[[binary]]
path = "/bin/userlist"
capability_profile = "coreutils.userlist"
kind = "application"
requires = [
    "ipc.client",
    "account.other.read",
]

[[binary]]
path = "/bin/useradd"
capability_profile = "coreutils.useradd"
kind = "application"
requires = [
    "ipc.client",
    "account.other.read",
    "account.other.modify",
    "fs.write.all",
]

[[binary]]
path = "/bin/userdel"
capability_profile = "coreutils.userdel"
kind = "application"
requires = [
    "ipc.client",
    "account.other.read",
    "account.other.modify",
    "fs.write.all",
]

[[binary]]
path = "/bin/mpk"
capability_profile = "coreutils.mpk"
kind = "application"
requires = [
    "ipc.client",
]

[[binary]]
path = "/bin/net"
capability_profile = "coreutils.net"
kind = "application"
requires = [
    "ipc.client",
    "net.connect",
    "net.tls.connect",
    "net.http.request",
]

[[binary]]
path = "/bin/test_gui"
capability_profile = "coreutils.test_gui"
kind = "application"
requires = [
    "ipc.client",
    "ipc.server",
    "window.create",
]

[[binary]]
path = "/bin/test_app"
capability_profile = "coreutils.test_app"
kind = "application"
requires = [
    "ipc.client",
    "ipc.server",
    "window.create",
]

[[binary]]
path = "/bin/test_desktop"
capability_profile = "coreutils.test_desktop"
kind = "application"
requires = [
    "ipc.client",
    "ipc.server",
    "window.create",
    "window.overlay",
]

[[binary]]
path = "/bin/selftest-ext2-write"
capability_profile = "coreutils.selftest-ext2-write"
kind = "application"
requires = [
    "fs.read.tmp",
    "fs.write.tmp",
]
